spring:
  data:
    neo4j:
      uri: ${NEO4J_URI}
      username: ${NEO4J_USER}
      password: ${NEO4J_PASSWORD}

server:
  port: 8181
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${CERTIFICATE_FOLDER}/${KEYSTORE_FILE}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-alias: ${KEY_ALIAS}

logging:
  file:
    name: ${LOG_PATH}/social_circle.log
  level:
    root: WARN
    org:
      springframework:
        web: INFO

identity-providers:
  facebook:
    url: ${FACEBOOK_API_URL}/v${FACEBOOK_API_VERSION}
    client-id: ${FACEBOOK_APP_ID}
    client-secret: ${FACEBOOK_APP_SECRET}