spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: secret

server:
  port: 8181

identity-providers:
  facebook:
    url: ${FACEBOOK_API_URL}
    client-id: ${FACEBOOK_APP_ID}
    client-secret: ${FACEBOOK_APP_SECRET}